---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: ingress-nginx
                # anything not staging or prod use this version
                addonChartVersion: 4.8.1
                addonChartRepository: https://kubernetes.github.io/ingress-nginx
              selector:
                matchExpressions:
                
                  - key: enable_aws_ingress_nginx
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: 4.8.1
          - clusters:
              selector:
                matchLabels:
                  environment: prod
              values:
                addonChartVersion: 4.8.1
  template:
    metadata:
      name: addon-{{.name}}-{{.values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.addons_repo_url}}'
          targetRevision: '{{.metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{.metadata.annotations.addons_repo_basepath}}control-plane/values/{{.values.addonChart}}/values.yaml

            values: |
              controller:
                service:
                  type: LoadBalancer
                  annotations:
                    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
                    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
                  loadBalancerClass: service.k8s.aws/nlb
      destination:
        namespace: '{{.values.addonChart}}'
        name: '{{.name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
