# your base domain needed to create aws certificate manager
base_domain: calebs.xyz
# specify a particular environment one of either "staging","prod" or "preview"
environment: staging
# specify a particular service/apps e.g web,api frontend,backend e.t.c
service: web
# specify subdomain specific to the specified environment
sub_domain: staging.calebs.xyz
# specify docker image  specific to the specified environment and service
image: horizonclient/calkube:v3.7.16
# specify docker images for all services in this environment,to be used by argocd image updater
# in this format: web=image:0.0.1,api=image_2:0.0.1
image_list: horizonclient/calkube:v3.7.15
# specify the number of deployment replicas for this particular environment and service
# defaults to 1
replicas: 1
# specify the port exposed by your app for specified environment and service
port: 80
# name of slack channel to send notfication if you want to enable argo notifications
slack_channel: alerts
# aws secret manager secrets name
secret_creds: creds
# Use git ssh to access all git repos using format git@github.com:<org>
enable_git_ssh: false
# AWS region to create kuberntes cluster
region: us-west-2
# Git repository org/user
git_owner: ChichiCaleb
# Git repository name
git_repo: argocd-terraform
# choose db engine
# only supports postgres engine for now
db_engine: postgres 
# enable addons deployed to control plane
addons:
  enable_argocd: true                       
  enable_argo_rollouts: true
  enable_argocd_image_updater: true          
  enable_aws_ebs_csi_resources: true          
  enable_external_secrets: true              
  enable_aws_load_balancer_controller: true   
  enable_karpenter:  true   
  enable_external_dns:  true 
  enable_grafana:  true     
  enable_loki_stack:   true 
  enable_cluster_proportional_autoscaler: true 
  enable_kube_prometheus_stack:  true        
  enable_kyverno:   true   
  enable_kubecost:  true 
# your app config and environment variables
config:
  NEXT_PUBLIC_WEBAPP_URL: staging.calebs.xyz
  NEXTAUTH_URL: staging.calebs.xyz/api/auth
  DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  NODE_ENV: production



