apiVersionOverrides:
  ingress: "networking.k8s.io/v1" 
controller:
 metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
dashboard:
  enabled: true
 
 
notifications:
  notifiers: 
    service.slack: |
      token: $slack-token
  
  defaultTriggers: |
    - on-rollout-completed
    - on-rollout-step-completed

  trigger.on-purple: |
    - send: [my-purple-template]
      when: rollout.spec.template.spec.containers[0].image == 'argoproj/rollouts-demo:purple'
  template.my-purple-template: |
    message: |
      Rollout {{.rollout.metadata.name}} has purple image
    slack:
        attachments: |
            [{
              "title": "{{ .rollout.metadata.name}}",
              "color": "#800080"
            }]