apiVersionOverrides:
  ingress: "networking.k8s.io/v1" 
controller:
 metrics:
    enabled: true
    
dashboard:
  enabled: true
 
 
notifications:
  # secret:
  #   create: true
  #   items: 
  #      slack-token:  "{{metadata.annotations.slack_token}}"
  notifiers: 
    service.slack: |
      token: $slack-token
  
  # defaultTriggers: |
  #   - on-rollout-completed
  #   - on-rollout-step-completed