apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: staging  
spec: 
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: db
  
  template: 
    metadata: 
      name: postgres
      labels: 
        app: db
    spec:
      initContainers:
      - name: busybox
        image: busybox:latest  
        args: ["rm","rf","/var/lib/postgresql/data/lost+found"]
        volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data    

      containers:
        - name: postgres
          image: postgres
          env:
           - name: POSTGRES_USER
             valueFrom:
              secretKeyRef:
                name: calcom-cred
                key:  POSTGRES_USER
           - name: POSTGRES_PASSWORD
             valueFrom:
              secretKeyRef:
                name: calcom-cred
                key:  POSTGRES_PASSWORD
        
          ports:
            - containerPort: 5432
              name: postgres 

          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data    
    

  volumeClaimTemplate:
  - metadata:
       name: postgres-persistent-storage
    spec:
      accessModes:
        -ReadWriteOnce
      storageClassName: "" 
      resources:
        requests:
          storage: 4Gi
            