    
    - target:
        kind: Deployment
        name: apps-deployment
      patch: |-
        - op: replace
          path: /metadata/name
          value: staging-web

        - op: replace
          path: /metadata/labels/apps
          value: staging-web

        - op: replace
          path: /spec/selector/matchLabels/apps
          value: staging-web

        - op: replace
          path: /spec/template/metadata/labels/apps
          value: staging-web
        
        - op: replace
          path: /spec/template/spec/containers/0/image
          value: horizonclient/calkube:v3.7.16

        - op: replace
          path: /spec/replicas
          value: 1

        - op: replace
          path: /spec/template/spec/containers/0/ports/0/containerPort
          value: 80

        - op: replace
          path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
          value: 80

        - op: replace
          path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
          value: 80

    - target:
        kind: Service
        name: apps-service
      patch: |-
        - op: replace
          path: /metadata/name
          value: staging-web

        - op: replace
          path: /spec/selector/apps
          value: staging-web

        - op: replace
          path: /spec/ports/0/port
          value: 80

        - op: replace
          path: /spec/ports/0/targetPort
          value: 80

    - target:
        kind: Service
        name: apps-prom
      patch: |-
        - op: replace
          path: /metadata/name
          value: staging-web

        - op: replace
          path: /spec/selector/apps
          value: staging-web

    - target:
        kind: Ingress
        name: apps-ingress
      patch: |-
        - op: replace
          path: /metadata/name
          value: staging-web

        - op: replace
          path: /spec/tls/0/hosts/0
          value: staging.calebs.xyz

        - op: replace
          path: /spec/rules/0/host
          value: staging.calebs.xyz

        - op: replace
          path: /spec/rules/0/http/paths/0/backend/service/name
          value: staging-web

        
        - op: replace
          path: /metadata/annotations/[alb.ingress.kubernetes.io/group.order]
          value: 9989

        - op: add
          path: /spec/rules/0/http/paths/0/backend/service/port
          value: number=80

    - target:
        kind: ExternalSecret
        name: external-secrets-sm
      patch: |-
        - op: replace
          path: /spec/dataFrom/0/extract/key
          value: creds

    - target:
        kind: ClusterSecretStore
        name: cluster-secretstore-sm
      patch: |-
        - op: replace
          path: /spec/provider/aws/region
          value: us-west-2
