apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-duplicate-service-ports
spec:
  validationFailureAction: enforce
  rules:
  - name: check-unique-ports
    match:
      resources:
        kinds:
        - Service
    validate:
      message: "Port numbers must be unique across services within the namespace."
      pattern:
        spec:
          ports:
          - key: "port"
            value: "{{request.object.spec.ports[*].port}}"
      anyOf:
      - pattern:
          - not:
              # Checks if the current service has any duplicate port numbers with other services in the namespace
              - eq:
                  - "{{request.namespace}}"
                  - "{{request.object.metadata.namespace}}"
              - eq:
                  - "{{request.object.spec.ports[*].port}}"
                  - "{{services.objects.metadata.namespace[request.namespace].spec.ports[*].port | unique }}"
