---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-duplicate-deployment-ports
spec:
  validationFailureAction: enforce
  rules:
  - name: check-unique-ports
    match:
      resources:
        kinds:
        - Deployment
    validate:
      message: "Port numbers must be unique across deployments within the namespace."
      pattern:
        spec.template.spec.containers[*].ports[*].containerPort:
          anyOf:
          - match:
              eq:
                "{{request.object.metadata.namespace}}": "{{request.namespace}}"
                
          - pattern:
              not:
                eq:
                  "{{request.object.spec.template.spec.containers[*].ports[*].containerPort}}": "{{deployments.objects.metadata.namespace[request.namespace].spec.template.spec.containers[*].ports[*].containerPort | unique }}"
                
