---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-duplicate-service-ports
spec:
  validationFailureAction: enforce
  rules:
  - name: check-unique-ports
    match:
      resources:
        kinds:
        - Service
    validate:
      message: "Port numbers must be unique across services within the namespace."
      pattern:
        spec.ports[*].port:
          anyOf:
          - match:
              eq:
                "{{request.object.metadata.namespace}}": "{{request.namespace}}"
          - pattern:
              not:
                eq:
                  "{{request.object.spec.ports[*].port}}": "{{services.objects.metadata.namespace[request.namespace].spec.ports[*].port | unique }}"
