apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: guestbook-ui
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: gcr.io/heptio-images/ks-guestbook-demo:0.2
      
    - op: replace
      path: /spec/replicas
      value: 1

- target:
    kind: Service
    name: guestbook-ui
  patch: |-
    - op: replace
      path: /metadata/name
      value: guestbook-ui-staging 

    - op: replace
      path: /spec/ports/0/port
      value: 8002

- target:
    kind: Ingress
    name: guestbook-ui 
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: staging.calebs.xyz
 
    - op: replace
      path: /spec/rules/0/host
      value: staging.calebs.xyz

    - op: replace
      path: /spec/rules/0/http/paths/0/backend/service/name
      value: guestbook-ui-staging

    - op: replace
      path: /spec/rules/0/http/paths/0/backend/service/port/number
      value: 8002







