apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: ingress
  metrics:
  - name: success-rate
    initialDelay: 60s
    interval: 5m
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address:  http://prometheus-kube-prometheus-prometheus.monitoring:9090
        query: |
          sum(rate(
            http_requests_total{ service="{{args.ingress}}", status!="500"}[5m]
          )) /
          sum(rate(
            http_requests_total{ service="{{args.ingress}}"}[5m]
          ))

# query: |
#           sum(rate(
#             http_requests_total{job="aws-alb-metrics", service="{{args.ingress}}", status!="500"}[5m]
#           )) /
#           sum(rate(
#             http_requests_total{job="aws-alb-metrics", service="{{args.ingress}}"}[5m]
#           ))