# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: app-monitor
#   labels:
#     release: prometheus
#     app: prometheus
#     prometheus: main
# spec:
#   endpoints:
#     - interval: 30s
#       port: http-metrics
#       path: /metrics
#   selector:
#     matchLabels:
#       app: app-monitoring