apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
- deployment.yaml
- namespace.yaml
- ingress.yaml
- secrets.yaml
- service.yaml

configMapGenerator:
- behavior: create
  envs:
  - environment-properties.env
  name: environment-variables
configurations:
- env-var-transformer.yaml
replacements:
- source:
    fieldPath: data.CERTIFICATE_ARN
    kind: ConfigMap
    name: environment-variables
    version: v1
  targets:
  - fieldPaths:
    - metadata.annotations.[alb.ingress.kubernetes.io/certificate-arn]
    select:
      group: networking.k8s.io
      kind: Ingress
      name: guestbook-ui
      version: v1
      
- source:
    fieldPath: data.REGION
    kind: ConfigMap
    name: environment-variables
    version: v1
  targets:
  - fieldPaths:
    - spec.provider.aws.region
    select:
      group: external-secrets.io
      kind: ClusterSecretStore
      name: cluster-secretstore-sm
      version: v1beta1

- source:
    fieldPath: data.SECRET_IDENTIFIER
    kind: ConfigMap
    name: environment-variables
    version: v1
  targets:
  - fieldPaths:
    - spec.dataFrom.0.extract.key
    select:
      group: external-secrets.io
      kind: ExternalSecret
      name: external-secrets-sm
      version: v1beta1

