---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
- name: environment-variables
  envs: [environment-properties.env]
  behavior: create

vars:
- name: CERTIFICATE_ARN
  objref:
    kind: ConfigMap
    name: environment-variables
    apiVersion: v1
  fieldref:
    fieldpath: data.CERTIFICATE_ARN

configurations:
  - env-var-transformer.yaml