apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
- deployment.yaml
- namespace.yaml
- ingress.yaml
configMapGenerator:
- behavior: create
  envs:
  - environment-properties.env
  name: environment-variables
configurations:
- env-var-transformer.yaml
replacements:
- source:
    fieldPath: data.CERTIFICATE_ARN
    kind: ConfigMap
    name: environment-variables
    version: v1
  targets:
  - fieldPaths:
    - metadata.annotations.[alb.ingress.kubernetes.io/certificate-arn]
    select:
      group: networking.k8s.io
      kind: Ingress
      name: guestbook-ui
      version: v1
