---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secretstore-sm
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets-sm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore-sm
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: creds