apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
- ../../base
- service.yaml
- rollout.yaml
- analysis-success-rate.yaml



patches:
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: guestbook-ui

- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: guestbook-ui
    spec:
      tls:
      - hosts:
        - calebs.xyz
      rules:
        - host: calebs.xyz
          http:
            paths:
              - path: /*
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: alb-rollout-root
                    port: 
                      number: use-annotation