apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
replicas:
- count: 1
  name: guestbook-ui
images:
- name: gcr.io/heptio-images/ks-guestbook-demo:0.2
    # newTag: v0.1.0

resources:
- ../../base

patches:
- target:
    kind: Service
    name: guestbook-ui
  patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: guestbook-ui
    spec:
     ports: 
      - port: 8000
        targetPort: 80

- target:
    kind: Ingress
    name: guestbook-ui
  patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: guestbook-ui
    spec:
      tls:
      - hosts:
        - calebs.xyz
      rules:
        - host: calebs.xyz
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: guestbook-ui
                    port: 
                      number: 8000